title: METS 2 Primer
description: Metadata Encoding and Transmission Standard (Version 2) Primer
author: METS Editorial Board
remote_theme: just-the-docs/just-the-docs

aux_links:
  METS primer on GitHub: https://github.com/METS/METS-primer

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
