title: METS 2 Guide
description: Metadata Encoding and Transmission Standard (Version 2) Guide
author: METS Editorial Board
remote_theme: just-the-docs/just-the-docs

aux_links:
  METS guide on GitHub: https://github.com/METS/METS-guide

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
